## Flutter wrapper
-keep class com.google.**{*;} 
-keepclassmembers class * implements java.io.Serializable { *; } 
-keep class com.baseflow.permissionhandler.** { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**